name: PyBootcampCondaOmar-chaim
dependencies:
  - python>=3.6,<3.10
  - pip==20.0.2
  - Flask==1.1.1
  - gunicorn==20.0.4
  - pytest==5.3.5
  - gevent==1.4.0
  - pip:
    - --index-url https://pypi.python.org/simple
    - flask-restx==0.2.0

